### ISSUE TITLE
Can't be loaded.

### ISSUE THREAD

**Issue by Kasdal** [Mkalo/macro-maker#4]
Hi Matt. 
I am getting this error 
Hoping you can help with this. 
Thank you.

```[14:18:23.245] [mods] ERROR: Module "Macro-Maker" could not be loaded!
[14:18:23.245] [mods] ERROR: Please contact the module's author: https://github.com/Mkalo/macro-maker/issues
[14:18:23.246] SyntaxError: Unexpected token P in JSON at position 72
    at JSON.parse (<anonymous>)
    at new MacroMaker (C:\Users\Milan\AppData\Local\Programs\TeraToolbox\mods\macro-maker-master\index.js:25:25)
    at ModuleManager.load (C:\Users\Milan\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:157:35)
    at C:\Users\Milan\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:122:22
    at Map.forEach (<anonymous>)
    at ModuleManager.loadAll (C:\Users\Milan\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:120:31)
    at Socket.<anonymous> (C:\Users\Milan\AppData\Local\Programs\TeraToolbox\bin\connectionManager.js:58:51)
    at Socket.emit (events.js:215:7)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1114:10)```

**Comment by Mkalo** [comment]
Your config.json file is wrong.
"Unexpected token P in JSON at position 72"

Post your config.json or use https://jsonlint.com/ to figure out where it is.

**Comment by Kasdal** [comment]
Yeah. My mistake. I only used 1 slash in the path. Loads now. Thank you.
